# Generated by Django 4.2.2 on 2023-06-17 11:48

import Expenses_App.my_web.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2, 'First name must be at least 2 chars!'), Expenses_App.my_web.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2, 'First name must be at least 2 chars!'), Expenses_App.my_web.validators.validate_only_letters])),
                ('budget', models.FloatField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', validators=[Expenses_App.my_web.validators.validate_image_size])),
            ],
        ),
    ]
