# Generated by Django 4.2.2 on 2023-06-17 13:10

import Expenses_App.my_web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(validators=[Expenses_App.my_web.models.validate_budget]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2, 'First name must be at least 2 chars!'), Expenses_App.my_web.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2, 'First name must be at least 2 chars!'), Expenses_App.my_web.models.validate_only_letters]),
        ),
    ]
