# Generated by Django 4.2.2 on 2023-06-17 13:11

import Expenses_App.my_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0005_alter_expense_price_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.FloatField(default=0, validators=[Expenses_App.my_web.models.validate_budget]),
        ),
    ]
