# Generated by Django 4.2.2 on 2023-06-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0006_alter_expense_price_alter_profile_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='1', upload_to='images'),
            preserve_default=False,
        ),
    ]
