# Generated by Django 4.2.2 on 2023-06-17 13:28

import Expenses_App.my_web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0009_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='images', validators=[Expenses_App.my_web.models.validate_file_size_5mb]),
        ),
    ]
